version: "3"
volumes:
  node_modules:
  build:
services:
  app:
    build: .
    env_file: .env
    command: bash -c "cd assets && npm install && cd .. && mix phx.server"
    volumes:
      - .:/app
      - node_modules:/app/assets/node_modules
      - build:/app/_build
    ports:
      - "4000:4000"
